spring:
    profiles:
      active: prod
busi:
  ops: Y
---
server:
  port: 8002
spring:
  datasource:
    druid:
      username: root
      password: 123456
      jdbcUrl: jdbc:mysql://192.168.1.108:3306/spring-cloud3
      driver-class-name: com.mysql.jdbc.Driver
  profiles: dev
  application:
      name: ms-provider-order
---
spring:
  datasource:
    druid:
      username: root
      password: 123456
      jdbcUrl: jdbc:mysql://192.168.1.108:3306/spring-cloud2
      driver-class-name: com.mysql.jdbc.Driver
  profiles: prod
  application:
      name: ms-provider-order
server:
  port: 8003
