spring:
    profiles:
      active: dev
    application:
      name: ms-provider-order
---
spring:
  datasource:
    druid:
      username: root
      password: 123456
      jdbcUrl: jdbc:mysql://47.104.128.12:3306/tuling-cloud
      driver-class-name: com.mysql.jdbc.Driver
  profiles: dev
---
spring:
  datasource:
    druid:
      username: root
      password: 123456
      jdbcUrl: jdbc:mysql://47.104.128.12:3306/tuling-cloud02
      driver-class-name: com.mysql.jdbc.Driver
  profiles: test