spring:
    profiles:
      active: dev
    application:
    	name: ms-provider-order  
busi:
  ops: N
---
spring:
  datasource:
    druid:
      username: root
      password: 123456
      jdbcUrl: jdbc:mysql://47.104.128.12:3306/tuling-cloud03
      driver-class-name: com.mysql.jdbc.Driver
  profiles: dev

server:
  port: 8002
---
spring:
  datasource:
    druid:
      username: root
      password: 123456
      jdbcUrl: jdbc:mysql://47.104.128.12:3306/tuling-cloud02
      driver-class-name: com.mysql.jdbc.Driver
  profiles: prod
server:
  port: 8003




