spring:
    profiles:
      active: dev
busi:
  ops: Y
---
spring:
  datasource:
    druid:
      username: root
      password: 123456
      jdbcUrl: jdbc:mysql://47.104.128.12:3306/tuling-cloud03
      driver-class-name: com.mysql.jdbc.Driver
  profiles: dev
  application: 
      name: ms-provider-order-8002
server:
  port: 8002
---
spring:
  datasource:
    druid:
      username: root
      password: 123456
      jdbcUrl: jdbc:mysql://47.104.128.12:3306/tuling-cloud02
      driver-class-name: com.mysql.jdbc.Driver
  profiles: test
  application: 
      name: ms-provider-order-8003
server:
  port: 8003




